apiVersion: v1
kind: Service
metadata:
  name: rknn-resnet18
spec:
  selector:
    app: rknn-resnet18
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rknn-resnet18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rknn-resnet18
  template:
    metadata:
      labels:
        app: rknn-resnet18
    spec:
      containers:
      - name: rknn-resnet18
        image: ghcr.io/elct9620/lab-rknn-resnet18
        securityContext:
          # NOTE: required due to the RKNPU limitation
          privileged: true
        resources:
          limits:
            rock-chips.com/rknpu: 1
        ports:
        - containerPort: 8080
